apiVersion: v2
name: tpm-device-plugin
type: application
description: A Helm chart for Kubernetes to deploy TPM device plugin

version: 1.0.0
appVersion: 1.0.0

maintainers:
  - name: 2gis
    url: https://github.com/2gis
    email: on-premise@2gis.com
