{{- with $.Values -}}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      containers:
        - name: tpm-device-plugin
          {{- $image_repository := required "A valid $.Values.image.repository should be configured" .image.repository }}
          {{- $image_tag := required "A valid $.Values.image.tag should be configured" .image.tag }}
          image: {{ $image_repository }}:{{ $image_tag }}
          imagePullPolicy: {{ .image.pullPolicy }}
          command: [ "tpm-device-plugin", "--domain", "{{ .domain }}" ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: tpm-device
              mountPath: /dev/tpmrm0
              readOnly: true
            - name: kubeletsockets
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: tpm-device
          hostPath:
            path: /dev/tpmrm0
        - name: kubeletsockets
          hostPath:
            path: /var/lib/kubelet/device-plugins

{{- end }}
